#! /bin/bash
source $DOTFILES/linux/log.sh

if pgrep -x "ncspot" >/dev/null; then
  log "An instance of ncspot is already running."
else
  log "Launching ncspot on Desktop 4"
  bspc rule -a "kitty" -o desktop="4" follow=off focus=off
  kitty -e fish -i -c ncspot &
fi
