#! /bin/sh
source $DOTFILES/linux/log.sh

LOG_FILE="$HOME/.bspwm.log"
exec 3>&1 1>${LOG_FILE} 2>&1

bspc monitor Virtual1 -d 1 2 3 4
bspc monitor Virtual2 -d 6 7 8 9

bspc config border_width		2
bspc config normal_border_color		"#0e1419"
bspc config active_border_color 	"#e6b450"
bspc config focused_border_color 	"#e6b673"

bspc config window_gap			    18
bspc config top_padding         0
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config ignore_ewmh_focus	  true


logins=$(find $DOTFILES -executable -type f -name login)

log "Sourcing login scripts:"
for login in $logins; do
  source $login
done
