#! /bin/sh
source $DOTFILES/linux/log.sh

log "Kill existing compton instance" &
killall compton &
log "Executing comton" &
compton -b --config $HOME/.config/compton/compton.conf &
log "Compton started" &
